### ISSUE TITLE
Getting "Cannot find builder "@angular-builders/custom-webpack:dev-server"

### ISSUE THREAD

**Issue by HamzaLJ** [meltedspark/angular-builders#319]
**Describe the bug**
When running `ng serve` I am getting the following :

```
Cannot find builder "@angular-builders/custom-webpack:dev-server"
```

**To Reproduce**
Run `ng serve`

```

Angular CLI: 8.0.0-rc.4
Node: 10.10.0
OS: darwin x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/pwa                      0.800.0-rc.4
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

The output of the error :

```
Cannot find builder "@angular-builders/custom-webpack:dev-server".
Error: Cannot find builder "@angular-builders/custom-webpack:dev-server".
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/Users/Hamza/Documents/Keeeb/compass/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:45:19)
    at ServeCommand.initialize (/Users/Hamza/Documents/Keeeb/compass/node_modules/@angular/cli/models/architect-command.js:135:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

**Comment by meltedspark** [comment]
You should use release candidate by installing either `@angular-builders/custom-webpack@8.0.0-RC.1` or `@angular-builders/custom-webpack@next`.
